CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS userPoints(
    id INTEGER PRIMARY KEY,
    id_user INTEGER NOT NULL,
    nbPoints INTEGER DEFAULT '0',
    boost INTEGER DEFAULT '1',
    FOREIGN KEY (id_user) REFERENCES user (id)
);

CREATE TABLE IF NOT EXISTS boostPrice(
    id_user INTEGER NOT NULL,
    price INTEGER DEFAULT '50',
    FOREIGN KEY (id_user) REFERENCES user (id)
);

CREATE TABLE IF NOT EXISTS store(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    libelle VARCHAR(25)
);